# Use the latest 2.1 version of CircleCI pipeline process engine.
# See: https://circleci.com/docs/2.0/configuration-reference
version: 2.1

orbs:
  python: circleci/python@2.0.3


# Define a job to be invoked later in a workflow.
# See: https://circleci.com/docs/2.0/configuration-reference/#jobs
jobs:
  tester:
    executor: python/default
    # docker:
    # - image: continuumio/miniconda3
    resource_class: small
    steps:
      - checkout
      - run:
          name: "Install prerequisites"
          command: pip install pytest sphinx dask matplotlib
      - run:
          name: "Install package"
          command: pip install .
      - run:
          name: "Run pytest"
          command: pytest
      - run:
          name: "Run sphinx doctest"
          command: sphinx-build -M doctest ./docs/source/ ./docs/build/
      - run:
          name: "Run sphinx linkcheck"
          command: sphinx-build -M linkcheck ./docs/source/ ./docs/build/

  publisher:
    executor: python/default
    # docker:
    # - image: continuumio/miniconda3
    resource_class: small
    steps:
      - checkout
      - run:
          name: "Install prerequisites"
          command: pip install twine build
      - run:
          name: "Build package"
          command: python -m build
      - run:
          name: "Upload using twine"
          command: twine upload dist/*


# Invoke jobs via workflows
# See: https://circleci.com/docs/2.0/configuration-reference/#workflows
workflows:
  main:
    jobs:
      - tester:
          filters:
            branches:
              ignore: release
      - publisher:
          filters:
            branches:
              only: release
