# Characteristics of the pipe and the effluent flow
[pipe]
csv.file = "pipe.csv"

# Characteristics of the ambient water masses
[ambient]
csv.file = "ambient.csv"

# Output options
[output]
csv.file = "out.csv"
csv.float_format = "%.4f"
trajectory.step = 5           # Time between trajectory points [s]
trajectory.stop = 100          # Time of final trajectory point [s]
release.start = 1970-01-01    # Time of first release [date]
release.stop = 1970-01-01     # Time of final release [date]
release.step = 3600           # Time between releases [s]
